apiVersion : apps/v1
kind: Deployment
metadata:
  name: "customeraks-94af"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "customeraks-94af"
  template:
    metadata:
      labels:
        app: "customeraks-94af"
    spec:
      containers:
        - name: "customeraks-94af"
          image: "managerreg.azurecr.io/customeraks"
          ports:
          - containerPort: 80